import React, { useState } from "react";
import api from "../services/api";
import { useTheme } from "../context/ThemeContext";

const getNormalizedCorrect = (question) => {
  const raw = String(question.correctAnswer || "").trim().toLowerCase();
  if (!Array.isArray(question.options)) return question.correctAnswer;
  const match = question.options.find(
    (opt) => String(opt).trim().toLowerCase() === raw
  );
  return match || question.correctAnswer;
};

const QuizPlayer = ({ questions, topic, difficulty, onBack }) => {
  const { theme } = useTheme();
  const [currentIndex, setCurrentIndex] = useState(0);
  const [score, setScore] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState(null);
  const [showExplanation, setShowExplanation] = useState(false);
  const [quizFinished, setQuizFinished] = useState(false);
  const [answers, setAnswers] = useState([]);

  if (!questions || !Array.isArray(questions) || questions.length === 0) {
    return (
      <div className={`p-12 text-center max-w-xl mx-auto rounded-3xl backdrop-blur-md border ${
        theme === "dark" ? "bg-[#11111a]/60 border-zinc-800" : "bg-white border-gray-200 shadow-xl"
      }`}>
        <h2 className={`text-lg font-bold mb-4 ${theme === "dark" ? "text-zinc-300" : "text-gray-700"}`}>No active context questions structural framework loaded.</h2>
        <button onClick={onBack} className="px-5 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl font-bold text-sm transition-all shadow-lg shadow-indigo-600/20">
          Return to Workspace
        </button>
      </div>
    );
  }

  const currentQuestion = questions[currentIndex];
  const normalizedCorrect = getNormalizedCorrect(currentQuestion);

  const handleAnswerClick = (option) => {
    if (selectedAnswer) return;

    setSelectedAnswer(option);
    setAnswers((prev) => {
      const next = [...prev];
      next[currentIndex] = option;
      return next;
    });
    setShowExplanation(true);

    if (option === normalizedCorrect) {
      setScore((prev) => prev + 1);
    }
  };

  const handleNext = () => {
    setSelectedAnswer(null);
    setShowExplanation(false);

    if (currentIndex + 1 < questions.length) {
      setCurrentIndex((prev) => prev + 1);
    } else {
      setQuizFinished(true);
    }
  };

  const handleSkip = () => {
    setSelectedAnswer(null);
    setShowExplanation(false);

    if (currentIndex + 1 < questions.length) {
      setCurrentIndex((prev) => prev + 1);
    } else {
      setQuizFinished(true);
    }
  };

  const handleFinish = async () => {
    if (topic && difficulty) {
      try {
        const resultsPayload = questions.map((q, index) => ({
          question: q.question,
          options: q.options,
          correctAnswer: q.correctAnswer,
          explanation: q.explanation,
          userAnswer: answers[index] || null,
        }));

        await api.post("/quiz/save-result", {
          topic,
          difficulty,
          score,
          totalQuestions: questions.length,
          questions: resultsPayload,
        });
      } catch (err) {
        console.error("Failed to automatically synchronize execution record logs:", err);
      }
    }
    onBack();
  };

  /* STATE VIEW 1: EVALUATION COMPLETE SUMMARY MATRIX PANEL */
  if (quizFinished) {
    const trackingPercentage = Math.round((score / questions.length) * 100);
    return (
      <div className={`p-6 sm:p-10 border rounded-3xl max-w-4xl mx-auto space-y-10 shadow-2xl backdrop-blur-xl animate-in fade-in duration-500 ${
        theme === "dark" ? "bg-[#11111a]/60 border-zinc-800/80" : "bg-white border-gray-200"
      }`}>
        
        {/* SCORE BANNER SEGMENT */}
        <div className={`text-center space-y-3 pb-6 border-b ${
          theme === "dark" ? "border-zinc-800/60" : "border-gray-200"
        }`}>
          <div className="inline-flex h-16 w-16 items-center justify-center bg-indigo-500/10 border border-indigo-500/20 rounded-2xl text-2xl mb-2 animate-bounce">
            🎉
          </div>
          <h2 className={`text-3xl font-black tracking-tight ${
            theme === "dark" ? "text-zinc-100" : "text-gray-900"
          }`}>Quiz Complete!</h2>
          <div className={`text-lg font-bold ${
            theme === "dark" ? "text-zinc-400" : "text-gray-600"
          }`}>
            Final Evaluation Score: <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-purple-400 text-2xl font-black ml-1">{score} / {questions.length} ({trackingPercentage}%)</span>
          </div>
          <p className={`text-xs max-w-md mx-auto leading-relaxed ${
            theme === "dark" ? "text-zinc-500" : "text-gray-500"
          }`}>
            Review detailed context trace insights generated by the system parsing layer below to analyze logic flaws.
          </p>
        </div>

        {/* LOG RECORD ITEM DISPLAY WRAPPER */}
        <div className="space-y-4 max-h-[440px] overflow-y-auto pr-2 scrollbar-thin scrollbar-thumb-zinc-800">
          {questions.map((q, index) => {
            const userAnswer = answers[index];
            const correct = getNormalizedCorrect(q);
            const isCorrect = userAnswer && String(userAnswer).trim().toLowerCase() === String(correct).trim().toLowerCase();

            return (
              <div
                key={index}
                className={`border rounded-2xl p-5 space-y-3 transition-colors ${
                  theme === "dark" 
                    ? "bg-[#0a0a0f]/80 border-zinc-800/60 hover:border-zinc-800" 
                    : "bg-gray-50 border-gray-200 hover:border-gray-300 shadow-sm"
                }`}
              >
                <div className="flex justify-between items-center text-xs font-bold text-zinc-500">
                  <span className={theme === "dark" ? "text-zinc-500" : "text-gray-400"}>Question Index {index + 1} of {questions.length}</span>
                  <span className={`px-2 py-0.5 rounded text-[10px] uppercase tracking-wider font-extrabold border ${
                    isCorrect 
                      ? (theme === "dark" ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" : "bg-emerald-100 text-emerald-700 border-emerald-200") 
                      : (theme === "dark" ? "bg-rose-500/10 text-rose-400 border-rose-500/20" : "bg-rose-100 text-rose-700 border-rose-200")
                  }`}>
                    {isCorrect ? "Correct" : "Incorrect"}
                  </span>
                </div>
                
                <p className={`font-bold text-base leading-snug ${
                  theme === "dark" ? "text-zinc-200" : "text-gray-800"
                }`}>{q.question}</p>
                
                <div className="space-y-1.5 pt-1 text-sm font-semibold">
                  <p className={isCorrect ? (theme === "dark" ? "text-emerald-400" : "text-emerald-600") : (theme === "dark" ? "text-rose-400/90" : "text-rose-600")}>
                    <span className={`font-medium ${theme === "dark" ? "text-zinc-500" : "text-gray-500"}`}>Your Input:</span> {userAnswer ?? "Skipped / Null selection field mapping"}
                  </p>
                  {!isCorrect && (
                    <p className={theme === "dark" ? "text-emerald-400" : "text-emerald-600"}>
                      <span className={`font-medium ${theme === "dark" ? "text-zinc-500" : "text-gray-500"}`}>Target Reference Match:</span> {correct}
                    </p>
                  )}
                </div>

                {q.explanation && (
                  <div className={`p-3 border rounded-xl mt-2 text-xs leading-relaxed ${
                    theme === "dark" ? "bg-zinc-900/40 border-zinc-800/40 text-zinc-400" : "bg-gray-100 border-gray-200 text-gray-600"
                  }`}>
                    <span className={`font-extrabold uppercase tracking-widest text-[9px] block mb-1 ${
                      theme === "dark" ? "text-zinc-500" : "text-gray-400"
                    }`}>AI Analytical Insight</span>
                    {q.explanation}
                  </div>
                )}
              </div>
            );
          })}
        </div>

        <div className="text-center pt-2">
          <button
            onClick={handleFinish}
            className="w-full sm:w-auto px-8 py-3.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white rounded-xl font-black text-sm tracking-widest uppercase shadow-xl shadow-indigo-600/10 transition-transform active:scale-95"
          >
            Save & Sync Run Results 💾
          </button>
        </div>
      </div>
    );
  }

  /* STATE VIEW 2: ACTIVE QUESTION RUNTIME RUN PLAYER */
  return (
    <div className={`max-w-3xl mx-auto p-5 sm:p-8 border rounded-3xl shadow-2xl backdrop-blur-xl animate-in fade-in duration-300 ${
      theme === "dark" ? "bg-[#11111a]/60 border-zinc-800/80" : "bg-white border-gray-200"
    }`}>
      
      {/* REAL-TIME PROGRESSIVE MONITORING HEADER BAR */}
      <div className="mb-8 space-y-3">
        <div className={`flex justify-between items-center text-xs font-black uppercase tracking-widest ${
          theme === "dark" ? "text-zinc-500" : "text-gray-400"
        }`}>
          <span>Question {currentIndex + 1} of {questions.length}</span>
          <span className={theme === "dark" ? "text-indigo-400" : "text-indigo-600"}>Target Segment</span>
        </div>
        <div className={`w-full rounded-full h-1.5 overflow-hidden border ${
          theme === "dark" ? "bg-zinc-900/80 border-zinc-800/20" : "bg-gray-200 border-gray-300"
        }`}>
          <div
            className="bg-gradient-to-r from-blue-500 via-indigo-500 to-purple-500 h-full rounded-full transition-all duration-300 ease-out"
            style={{ width: `${((currentIndex + 1) / questions.length) * 100}%` }}
          />
        </div>
      </div>

      {/* ITEM TEXT CONTENT QUESTION CORE BLOCK */}
      <div className="min-h-[72px] flex items-center mb-8">
        <h3 className={`text-lg sm:text-xl font-extrabold leading-relaxed tracking-tight ${
          theme === "dark" ? "text-zinc-100" : "text-gray-800"
        }`}>
          {currentQuestion.question}
        </h3>
      </div>

      {/* EVALUATION MULTIPLE SELECT OPTION STACK */}
      <div className="space-y-3 mb-6">
        {Array.isArray(currentQuestion.options) && currentQuestion.options.map((option, index) => {
          const isSelected = selectedAnswer === option;
          const isTargetMatch = option === normalizedCorrect;
          
          let optionStyles = theme === "dark"
            ? "bg-[#0a0a0f]/60 text-zinc-300 border-zinc-800/80 hover:border-zinc-700 hover:bg-zinc-900/30"
            : "bg-gray-50 text-gray-700 border-gray-200 hover:border-gray-300 hover:bg-gray-100/50";

          if (selectedAnswer !== null) {
            if (isSelected) {
              optionStyles = isTargetMatch 
                ? (theme === "dark" ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/40 shadow-inner" : "bg-emerald-100 text-emerald-700 border-emerald-300 shadow-inner") 
                : (theme === "dark" ? "bg-rose-500/10 text-rose-400 border-rose-500/40 shadow-inner" : "bg-rose-100 text-rose-700 border-rose-300 shadow-inner");
            } else if (isTargetMatch) {
              // Highlight where the correct answer was if the user picked wrong
              optionStyles = theme === "dark"
                ? "bg-emerald-500/5 text-emerald-400/80 border-emerald-500/20"
                : "bg-emerald-50/70 text-emerald-700 border-emerald-200";
            } else {
              optionStyles = theme === "dark"
                ? "bg-transparent text-zinc-600 border-zinc-900/60 opacity-40"
                : "bg-transparent text-gray-400 border-gray-200 opacity-40";
            }
          }

          return (
            <button
              key={index}
              onClick={() => handleAnswerClick(option)}
              disabled={selectedAnswer !== null}
              className={`w-full block text-left p-4 rounded-xl font-medium border text-sm sm:text-base transition-all transform active:scale-[0.995] duration-200 disabled:transform-none ${optionStyles}`}
            >
              <div className="flex items-center justify-between">
                <span>{option}</span>
                {selectedAnswer !== null && isSelected && (
                  <span>{isTargetMatch ? "✓" : "❌"}</span>
                )}
              </div>
            </button>
          );
        })}
      </div>

      {/* CONDITIONAL AI INSIGHT EXPLANATION DRAWER */}
      <div className={`transition-all duration-300 overflow-hidden ${showExplanation ? "max-h-[260px] opacity-100 mb-8" : "max-h-0 opacity-0 pointer-events-none"}`}>
        <div className={`p-5 rounded-2xl border space-y-2 ${
          theme === "dark" ? "bg-[#0a0a0f]/90 border-zinc-800/80" : "bg-gray-50 border-gray-200"
        }`}>
          <div className="flex items-center gap-2 text-xs font-black uppercase tracking-widest">
            {selectedAnswer === normalizedCorrect ? (
              <span className="text-emerald-500">✓ Core System Validation Passed</span>
            ) : (
              <span className="text-rose-500">⚠️ Analytical Exception Triggered</span>
            )}
          </div>
          
          {selectedAnswer !== normalizedCorrect && (
            <p className={`text-xs font-semibold ${theme === "dark" ? "text-zinc-400" : "text-gray-600"}`}>
              Expected Object Value Mapping: <span className={theme === "dark" ? "text-emerald-400" : "text-emerald-600"}>{normalizedCorrect}</span>
            </p>
          )}

          {currentQuestion.explanation && (
            <div className={`pt-2 border-t text-xs leading-relaxed ${
              theme === "dark" ? "border-zinc-800/40 text-zinc-400" : "border-gray-200 text-gray-600"
            }`}>
              <span className={`font-bold block mb-1 text-[10px] uppercase tracking-wide ${theme === "dark" ? "text-zinc-500" : "text-gray-500"}`}>Context Explanation:</span>
              {currentQuestion.explanation}
            </div>
          )}
        </div>
      </div>

      {/* CORE RUN PLAYER FOOTER ACTIONS PANEL */}
      <div className={`pt-4 border-t flex gap-4 justify-end items-center ${
        theme === "dark" ? "border-zinc-800/40" : "border-gray-200"
      }`}>
        <button
          onClick={handleSkip}
          disabled={selectedAnswer !== null}
          className={`px-5 py-2.5 rounded-xl font-bold text-xs uppercase tracking-wider transition-all disabled:opacity-30 disabled:cursor-not-allowed border ${
            theme === "dark"
              ? "bg-zinc-900/60 hover:bg-zinc-900 border-zinc-800/80 text-zinc-400 hover:text-zinc-200"
              : "bg-gray-100 hover:bg-gray-200 border-gray-200 text-gray-600 hover:text-gray-800"
          }`}
        >
          Skip Element
        </button>
        <button
          onClick={handleNext}
          disabled={!selectedAnswer && !showExplanation}
          className="px-6 py-2.5 bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-500 hover:to-indigo-500 text-white rounded-xl font-bold text-xs uppercase tracking-wider transition-all disabled:opacity-40 disabled:cursor-not-allowed shadow-lg shadow-indigo-600/10"
        >
          {currentIndex + 1 === questions.length ? "Finish Evaluation" : "Next Field ➡️"}
        </button>
      </div>
    </div>
  );
};

export default QuizPlayer;